version: '3'

services:
  registry:
      image: registry:2
      container_name: registry
      restart: always
      volumes:
        - ./registry_data:/var/lib/registry
        - ./config.yml:/etc/docker/registry/config.yml

  proxy:
    image: nginx
    container_name: registry_proxy
    volumes:
      - ./nginx-proxy/proxy_data:/data
      - ./nginx-proxy/proxy_data/conf/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "80:80"
      - "443:443"
