version: '3'

services:
  registry:
      image: registry:2
      env_file: .env
      restart: always
      ports:
        - "5000:5000"
      volumes:
        - registry_data:/var/lib/registry
        - ./config.yml:/etc/docker/registry/config.yml

volumes:
  registry_data:
