version: '3'

services:
  registry:
      image: registry:2
      env_file: .env
      restart: always
      volumes:
        - ./registry_data:/var/lib/registry
        - ./config.yml:/etc/docker/registry/config.yml
  proxy:
    build:
      context: nginx-proxy
      args:
        PROXY_SSL: $PROXY_SSL
        PROXY_DOMAIN: $PROXY_DOMAIN
    volumes:
      - ./nginx-proxy/proxy_data:/data
    restart: always
    deploy:
      restart_policy:
        condition: always
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
