version: '3'

services:
  registry:
    image: registry:2
    restart: always
    volumes:
      - registry_data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
  registrymanager:
    image: registrymanager:latest
    env_file: .registry.env
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/certs:/certs
  database:
    image: postgres:10
    volumes:
      - userdatabase:/var/lib/postgresql
    env_file: .registry.env

volumes:
  registry_data:
  userdatabase:
